"""Curated neuron populations.

The FlyWire-derived dataset ships **no cell-type annotation** — its neuron table
has a single ``Completed`` column (see ``docs/UPSTREAM_AUDIT.md`` section 5 and
the ``neuron_types_available`` warning in ``outputs/dataset_report.json``). The
only neuron-type information available to FlyBrain is therefore the curated set of
input lists declared in the upstream repositories, which this module loads from
``populations.json``.

That file is generated by parsing the upstream notebooks with ``ast`` rather than
retyping IDs, and it records the SHA-256 of every source file it was parsed from,
so the lists can be re-derived and checked. Retyping 114 lists of 20-digit
integers by hand is exactly the kind of step that silently corrupts a simulation.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Sequence, Tuple

import numpy as np

from ..errors import FlyBrainError, UnknownPopulationError

_REGISTRY_FILE = Path(__file__).with_name("populations.json")


@dataclass(frozen=True)
class Population:
    """A named group of neurons, addressed by FlyWire ID."""

    name: str
    ids: Tuple[int, ...]
    description: str = ""
    upstream_symbol: str = ""

    def __len__(self) -> int:
        return len(self.ids)

    def __iter__(self) -> Iterator[int]:
        return iter(self.ids)

    def __contains__(self, flywire_id: object) -> bool:
        return int(flywire_id) in self.ids  # type: ignore[arg-type]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "ids": list(self.ids),
            "n_neurons": len(self.ids),
            "description": self.description,
            "upstream_symbol": self.upstream_symbol,
        }


class PopulationRegistry:
    """Name -> :class:`Population`, loaded from the packaged JSON."""

    def __init__(
        self,
        populations: Dict[str, Population],
        metadata: Optional[Dict[str, Any]] = None,
    ):
        self._populations = dict(populations)
        self.metadata = metadata or {}

    # -- construction --------------------------------------------------------------
    @classmethod
    def builtin(cls) -> "PopulationRegistry":
        return cls.from_file(_REGISTRY_FILE)

    @classmethod
    def from_file(cls, path: str | Path) -> "PopulationRegistry":
        path = Path(path)
        if not path.is_file():
            raise FlyBrainError(
                f"population registry not found: {path}. It is package data; "
                f"reinstall FlyBrain or regenerate it from the upstream notebooks."
            )
        doc = json.loads(path.read_text(encoding="utf-8"))
        pops = {}
        for name, entry in doc.get("populations", {}).items():
            ids = tuple(sorted({int(x) for x in entry["ids"]}))
            pops[name] = Population(
                name=name,
                ids=ids,
                description=entry.get("description", ""),
                upstream_symbol=entry.get("upstream_symbol", ""),
            )
        return cls(pops, metadata={k: v for k, v in doc.items() if k != "populations"})

    # -- lookup --------------------------------------------------------------------
    def names(self) -> List[str]:
        return sorted(self._populations)

    def __contains__(self, name: object) -> bool:
        return name in self._populations

    def __len__(self) -> int:
        return len(self._populations)

    def __iter__(self) -> Iterator[Population]:
        return iter(self._populations[n] for n in self.names())

    def get(self, name: str) -> Population:
        try:
            return self._populations[name]
        except KeyError:
            raise UnknownPopulationError(
                f"unknown population {name!r}. Try `flybrain populations` to list them, "
                f"or `flybrain populations --search <text>`."
            ) from None

    def find(self, pattern: str) -> List[Population]:
        """Case-insensitive substring search over names and descriptions."""
        p = pattern.lower()
        return [
            pop
            for pop in self
            if p in pop.name.lower() or p in pop.description.lower()
        ]

    def resolve(self, name: str, flywire_ids: Sequence[int] | np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """Split a population into (IDs present in the dataset, IDs missing).

        Missing IDs are reported rather than raised on: the whole point of a
        registry that spans two dataset versions is that some members will be
        absent, and the caller needs to know *which*.
        """
        pop = self.get(name)
        present_set = set(int(x) for x in flywire_ids)
        present = np.fromiter((i for i in pop.ids if i in present_set), dtype=np.int64)
        missing = np.fromiter((i for i in pop.ids if i not in present_set), dtype=np.int64)
        return present, missing
